# Generated by Django 4.2.27 on 2026-01-01 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# class Migration(migrations.Migration):

#     dependencies = [
#         ('db', '0112_auto_20251124_0603'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='TrackedTime',
#             fields=[
#                 ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
#                 ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
#                 ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
#                 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
#                 ('total_spent_time', models.DurationField(default=datetime.timedelta(0), verbose_name='Total Accumulated Time')),
#                 ('description', models.TextField(blank=True, null=True)),
#                 ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
#                 ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to='db.issue')),
#                 ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to='db.project')),
#                 ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
#                 ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to=settings.AUTH_USER_MODEL)),
#             ],
#             options={
#                 'verbose_name': 'Tracked Time',
#                 'verbose_name_plural': 'Tracked Times',
#                 'db_table': 'tracked_time',
#                 'ordering': [],
#             },
#         ),
#     ]
# Generated by Django 4.2.27 on 2026-01-01 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_tracked_time_table(apps, schema_editor):
    """Create tracked_time table only if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        # Use CREATE TABLE IF NOT EXISTS for PostgreSQL
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tracked_time (
                id UUID PRIMARY KEY,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                deleted_at TIMESTAMP WITH TIME ZONE,
                total_spent_time INTERVAL NOT NULL DEFAULT '0',
                description TEXT,
                created_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
                updated_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                issue_id UUID REFERENCES issues(id) ON DELETE CASCADE
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # This updates Django's internal state about the model
                migrations.CreateModel(
                    name='TrackedTime',
                    fields=[
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                        ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('total_spent_time', models.DurationField(default=datetime.timedelta(0), verbose_name='Total Accumulated Time')),
                        ('description', models.TextField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                        ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to='db.issue')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to='db.project')),
                        ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_times', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Tracked Time',
                        'verbose_name_plural': 'Tracked Times',
                        'db_table': 'tracked_time',
                        'ordering': [],
                    },
                ),
            ],
            database_operations=[
                # This runs the actual database command
                migrations.RunPython(create_tracked_time_table, migrations.RunPython.noop),
            ],
        ),
    ]
