# Generated by Django 4.2.27 on 2026-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_retroboard_retroitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='retro_view',
            field=models.BooleanField(default=False),
        ),
    ]
