# Generated by Django 4.2.27 on 2026-03-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_project_retro_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='point',
        ),
        migrations.AddField(
            model_name='issue',
            name='estimate_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_time_estimates', to='db.estimatepoint'),
        ),
        migrations.AddField(
            model_name='issueversion',
            name='estimate_time',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
