# Generated by Django 4.2.27 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_remove_issue_point_issue_estimate_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatepoint',
            options={'ordering': ('key',), 'verbose_name': 'Estimate Point', 'verbose_name_plural': 'Estimate Points'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='type',
            field=models.CharField(choices=[('categories', 'Categories'), ('points', 'Points'), ('time', 'Time')], default='points', max_length=255),
        ),
    ]
