# Generated by Django 4.2.27 on 2026-03-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0117_alter_estimatepoint_options_alter_estimate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='uat_status',
            field=models.CharField(choices=[('#B80000', 'Red'), ('#008B02', 'Green'), ('#FFBF00', 'Amber')], default='#FFBF00', max_length=7, verbose_name='UAT Status'),
        ),
    ]
