# Generated by Django 4.2.27 on 2026-04-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0118_cycle_uat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='uat_status',
            field=models.CharField(choices=[('#000000', 'Black'), ('#D32F2F', 'Red'), ('#388E3C', 'Green'), ('#FBC02D', 'Amber')], default='#FFBF00', max_length=7, verbose_name='UAT Status'),
        ),
    ]
